#define KEYWORD 1
#define IDENTIFIER 2
#define CONSTANT 3
#define STRING_LITERAL 4
#define PUNCTUATORS 5
#define UNSIGNED 6
#define IF 7
#define BREAK 8
#define CASE 9
#define FLOAT 10
#define FOR 11
#define SIGNED 12
#define BOOL 13
#define CONTINUE 14
#define DO 15
#define INT 16
#define LONG 17
#define ELSE 18
#define RETURN 19
#define VOID 20
#define CHAR 21
#define SHORT 22
#define WHILE 23
#define GOTO 24
#define DEFAULT 25
#define SWITCH 26
#define DOUBLE 27
#define MATRIX 28

